name: Build OpenPoster

on:
  workflow_dispatch:

jobs:
  build-macos-intel:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MacOS (Intel)
        run: python3 compile.py

      - name: Zip OpenPoster.app (Intel)
        run: |
          cd dist
          zip -r -y "OpenPoster_macOS_intel.zip" OpenPoster.app

      - name: Upload ZIP (Intel)
        uses: actions/upload-artifact@v4
        with:
          name: OpenPoster_macOS_intel
          path: dist/OpenPoster_macOS_intel.zip

  build-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MacOS (ARM)
        run: python3 compile.py

      - name: Zip OpenPoster.app (ARM)
        run: |
          cd dist
          zip -r -y "OpenPoster_macOS_arm.zip" OpenPoster.app

      - name: Upload ZIP(ARM)
        uses: actions/upload-artifact@v4
        with:
          name: OpenPoster_macOS_arm
          path: dist/OpenPoster_macOS_arm.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows
        run: python compile.py

      - name: Zip OpenPoster
        run: |
          cd dist
          Compress-Archive -Path OpenPoster -DestinationPath "OpenPoster_Windows.zip"

      - name: Upload ZIP (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: OpenPoster_Windows
          path: dist/OpenPoster_Windows.zip
